version: '2'
services:
  balancer:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/mikhail/PycharmProjects/publicpage/balancer/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/mikhail/PycharmProjects/publicpage/static:/static/


  flaskserver:
    build: flaskserver
    restart: always




